x-analyze-volumes: &analyze-volumes
  volumes:
    - ./pgfr_analyze/install.sql:/analyze.sql:ro
    - ./pgfr_analyze/sql:/analyze_sql:ro
    - ./pgfr_analyze/tests:/tests/analyze:ro

services:
  postgres15:
    <<: *analyze-volumes
  postgres16:
    <<: *analyze-volumes
  postgres17:
    <<: *analyze-volumes
